clusters:
- alias: hasura
  data: null
  infra:
    provider: hasura-free
- alias: prod
  data: null
  infra:
    nodes:
    - labels:
        app: postgres
      type: s-2vcpu-4gb
    provider: digital-ocean
    region: blr1
    version: v1
    volumes:
    - name: postgres
      size: 10
    - name: filestore
      size: 10
    - name: sessionstore
      size: 2
version: v1
